# Generated by Django 4.0.5 on 2022-06-28 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='packing_charge',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='tax',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='additional_information',
            name='detail',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='additional_information',
            name='specification',
            field=models.CharField(max_length=200),
        ),
    ]
